USE master
GO

PRINT 'Alter the sa login'
GO

ALTER LOGIN [sa] WITH NAME = [$(MSSQL_SA_USERNAME)]
GO

PRINT 'Alter the sa login (done)'
GO

DROP DATABASE IF EXISTS AdventureWorks
GO
CREATE DATABASE AdventureWorks
GO

ALTER DATABASE AdventureWorks
SET RECOVERY SIMPLE,
    ANSI_NULLS ON,
    ANSI_PADDING ON,
    ANSI_WARNINGS ON,
    ARITHABORT ON,
    CONCAT_NULL_YIELDS_NULL ON,
    QUOTED_IDENTIFIER ON,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    ALLOW_SNAPSHOT_ISOLATION OFF;
GO

DROP DATABASE IF EXISTS Northwind
GO
CREATE DATABASE Northwind
GO

ALTER DATABASE Northwind
SET RECOVERY SIMPLE,
    ANSI_NULLS ON,
    ANSI_PADDING ON,
    ANSI_WARNINGS ON,
    ARITHABORT ON,
    CONCAT_NULL_YIELDS_NULL ON,
    QUOTED_IDENTIFIER ON,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    ALLOW_SNAPSHOT_ISOLATION OFF;
GO

DROP DATABASE IF EXISTS [TestMain];
DROP DATABASE IF EXISTS [TestSecondary];
GO

CREATE DATABASE [TestMain];
CREATE DATABASE [TestSecondary];
GO

USE [TestMain];
GO

CREATE SCHEMA [SchemaSmith]
GO

CREATE TABLE SchemaSmith.TestLog (Id INT IDENTITY(1,1) NOT NULL, Msg NVARCHAR(2000) NOT NULL)
GO
GO

USE [TestSecondary];
GO

CREATE SCHEMA [SchemaSmith]
GO

CREATE TABLE SchemaSmith.TestLog (Id INT IDENTITY(1,1) NOT NULL, Msg NVARCHAR(2000) NOT NULL)
GO
